name: Check Workspace Modifications

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - "accounts/**"

jobs:
  validate-workspace-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files (Only in accounts/)
        id: changed-files
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }} --depth=1
          CHANGED_FILES=$(git diff --name-only origin/${{ github.event.pull_request.base.ref }} HEAD | grep '^accounts/' || true)

          # If there are no relevant changes, exit early
          if [[ -z "$CHANGED_FILES" ]]; then
            echo "No relevant changes in accounts/ directory."
            exit 0
          fi

          echo "$CHANGED_FILES" > changed_files.txt

      - name: Extract unique workspaces
        id: check-workspaces
        run: |
          WORKSPACES=$(cat changed_files.txt | awk -F'/' '{print $1 "/" $2 "/" $3}' | sort -u)
          echo "Modified workspaces:"
          echo "$WORKSPACES"

          UNIQUE_COUNT=$(echo "$WORKSPACES" | wc -l)          
          echo "workspace_count=$UNIQUE_COUNT" >> $GITHUB_ENV

          WORKSPACE_PATH=$(echo "$WORKSPACES" | head -n 1)
          echo "$WORKSPACE_PATH" > workspace_path.txt

      # - name: Upload workspace path as artifact
      #   if: success()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: workspace-path
      #     path: workspace_path.txt

      - name: Fail if multiple workspaces are modified
        if: ${{ env.workspace_count > 1 }}
        run: |
          echo "❌ Multiple workspaces were modified in this PR. Please limit changes to a single workspace."
          exit 1