name: Terraform Lint

on:
  workflow_dispatch:
    inputs:
      account:
        description: "Target account"
        required: true
        type: string
      initiator:
        description: "User who triggered the workflow"
        required: false
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Print Received Parameters
        run: |
          echo "Running Terraform for submodule: ${{ github.event.inputs.account }}"
          echo "Triggered by: ${{ github.event.inputs.initiator }}"


      - name: Run Terraform Plan
        run: |
          echo "RUNNING"
