name: Terraform Lint

on:
  workflow_dispatch:
    inputs:
      account:
        description: "Target account"
        required: true
        type: string
      initiator:
        description: "User who triggered the workflow"
        required: false
        type: string

jobs:
  tflint:
    name: Run TFLint on accounts/${{ github.event.inputs.account }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Print Received Parameters
        run: |
          echo "Running tflint for account/${{ github.event.inputs.account }}"
          echo "Triggered by: ${{ github.event.inputs.initiator }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Run TFLint
        run:  tflint --format=compact | tee tflint.log

      - name: Upload TFLint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tflint-report
          path: tflint.log
