name: Terraform Lint

on:
  workflow_run:
    workflows: ["Check Workspace Modifications"]
    types:
      - completed

jobs:
  tflint:
    name: Run TFLint on changed workspace
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download workspace path
        uses: actions/download-artifact@v4
        with:
          name: workspace-path

      - name: Read workspace path
        id: read-path
        run: |
          echo "*************"
          WORKSPACE_PATH=$(cat workspace_path.txt)
          echo "Workspace Path: $WORKSPACE_PATH"
          echo "workspace_path=$WORKSPACE_PATH" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init

      - name: Run Terraform Linter in the changed workspace
        run: |
          echo "🚀 Running Terraform linting in ${{ env.workspace_path }}..."
          tflint --chdir=${{ env.workspace_path }} --format=compact | tee tflint.log

      - name: Upload TFLint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tflint-report
          path: tflint.log
